### ISSUE TITLE
lodash3/matches-shorthand listener must be a function

### ISSUE THREAD

**Issue by gajus** [wix/eslint-plugin-lodash3#13]
```
TypeError: Error while loading rule 'lodash3/matches-shorthand': listener must be a function
    at EventEmitter.addListener (events.js:197:11)
    at /Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/node_modules/eslint/lib/eslint.js:699:29
    at Array.forEach (native)
    at /Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/node_modules/eslint/lib/eslint.js:698:39
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/node_modules/eslint/lib/eslint.js:671:16)
    at processText (/Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/node_modules/eslint/lib/cli-engine.js:230:27)
    at CLIEngine.executeOnText (/Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/node_modules/eslint/lib/cli-engine.js:686:26)
    at exports.lintText.lintText (/Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/dist/linters/js/index.js:31:16)
    at exports.default (/Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/dist/lintText.js:46:35)
    at /Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/dist/lintFiles.js:65:45
    at arrayEach (/Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/node_modules/lodash/internal/arrayEach.js:15:9)
    at /Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/node_modules/lodash/internal/createForEach.js:15:9
    at exports.default (/Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/node_modules/canonical/dist/lintFiles.js:53:27)
    at /Users/gajus/Documents/dev/gajus/create-index/node_modules/pragmatist/dist/index.js:242:47
```

**Comment by gajus** [comment]
I am getting this error with the latest version regardless of the input code.

**Comment by ganimomer** [comment]
Hi @gajus,
The latest version made a breaking change in this rule (that's why the latest version had a larger minor version and not just a patch).
Change your configuration to match the one in the README or the rule docs, and it should fix it.

**Comment by gajus** [comment]
https://github.com/wix/eslint-plugin-lodash3/blob/master/docs/rules/matches-shorthand.md

Breaking change was introduced:

What was:

```json
"lodash3/matches-shorthand": [
    1,
    3
],
```

is now:

```json
"lodash3/matches-shorthand": [
    1,
    "always",
    3
],
```

**Comment by ganimomer** [comment]
Unfortunately, this is the message ESLint supplies whenever the rule config doesn't match the schema.
